namespace WebApi.Services;

public class SiteProvider : BaseProvider{
    ApThapNhietDoiRepository apthapnhietdoi = null!;
    BaoRepository bao = null!;
    BienCanhBaoSatLoRepository biencanhbaosatlo = null!;
    CongDapRepository congdap = null!;
    DeBaoBoBaoRepository debaobobao = null!;
    DiemAnToanRepository diemantoan = null!;
    DiemXungYeuRepository diemxungyeu = null!;
    DoManRepository doman = null!;
    DuKienDiDanRepository dukiendidan = null!;
    HuongDiChuyenRepository huongdichuyen = null!;
    KeRepository ke = null!;
    LocXoayRepository locxoay = null!;
    LucLuongHuyDongRepository lucluonghuydong = null!;
    MocCanhBaoTrieuCuongRepository moccanhbaotrieucuong = null!;
    MuaRepository mua = null!;
    MucNuocRepository mucnuoc = null!;
    NangNongRepository nangnong = null!;
    PhuongTienHuyDongRepository phuongtienhuydong = null!;
    SatLoLineRepository satloline = null!;
    SatLoPointRepository satlopoint = null!;
    ThietHaiThienTaiRepository thiethaithientai = null!;
    TuLieuHinhAnhRepository tulieuhinhanh = null!;
    TuLieuKhacRepository tulieukhac = null!;
    TuLieuVideoRepository tulieuvideo = null!;
    RanhGioiHuyenRepository ranhgioihuyen = null!;
    RanhGioiXaRepository ranhgioixa = null!;
    MemberRepository member = null!;
    GiaoThongRepository giaothong = null!;
    ThuyHeRepository thuyhe = null!;
    MemberRoleRepository memberrole = null!;
    MemberLoginRepository memberlogin = null!;
    HoChuaRepository hoChua = null!;
    Helper helper = null!;
    RoleRepository role = null!;
    RefreshTokenRepository refreshtoken = null!;
    ChayRungRepository chayrung = null!;    
    KhuNeoDauRepository khuneodau = null!; 
    DanhBaDTRepository danhBaDT = null!; 
    QuanDaoHSTSRepository quanDaoHSTS = null!;
    HistoryRepository history = null!;

    public SiteProvider(IConfiguration configuration) : base(configuration){}

    public ApThapNhietDoiRepository ApThapNhietDoi => apthapnhietdoi ??= new ApThapNhietDoiRepository(Connection);
    public BaoRepository Bao => bao ??= new BaoRepository(Connection);
    public BienCanhBaoSatLoRepository BienCanhBaoSatLo => biencanhbaosatlo ??= new BienCanhBaoSatLoRepository(Connection);
    public CongDapRepository CongDap => congdap ??= new CongDapRepository(Connection);
    public DeBaoBoBaoRepository DeBaoBoBao => debaobobao ??= new DeBaoBoBaoRepository(Connection);
    public DiemAnToanRepository DiemAnToan => diemantoan ??= new DiemAnToanRepository(Connection);
    public DiemXungYeuRepository DiemXungYeu => diemxungyeu ??= new DiemXungYeuRepository(Connection);
    public DoManRepository DoMan => doman ??= new DoManRepository(Connection);
    public DuKienDiDanRepository DuKienDiDan => dukiendidan ??= new DuKienDiDanRepository(Connection);
    public HuongDiChuyenRepository HuongDiChuyen => huongdichuyen ??= new HuongDiChuyenRepository(Connection);
    public KeRepository Ke => ke ??= new KeRepository(Connection);
    public LocXoayRepository LocXoay => locxoay ??= new LocXoayRepository(Connection);
    public LucLuongHuyDongRepository LucLuongHuyDong => lucluonghuydong ??= new LucLuongHuyDongRepository(Connection);
    public MocCanhBaoTrieuCuongRepository MocCanhBaoTrieuCuong => moccanhbaotrieucuong ??= new MocCanhBaoTrieuCuongRepository(Connection);
    public MuaRepository Mua => mua ??= new MuaRepository(Connection);
    public MucNuocRepository MucNuoc => mucnuoc ??= new MucNuocRepository(Connection);
    public NangNongRepository NangNong => nangnong ??= new NangNongRepository(Connection);
    public PhuongTienHuyDongRepository PhuongTienHuyDong => phuongtienhuydong ??= new PhuongTienHuyDongRepository(Connection);
    public SatLoLineRepository SatLoLine => satloline ??= new SatLoLineRepository(Connection);
    public SatLoPointRepository SatLoPoint => satlopoint ??= new SatLoPointRepository(Connection);
    public ThietHaiThienTaiRepository ThietHaiThienTai => thiethaithientai ??= new ThietHaiThienTaiRepository(Connection);
    public TuLieuHinhAnhRepository TuLieuHinhAnh => tulieuhinhanh ??= new TuLieuHinhAnhRepository(Connection);
    public TuLieuKhacRepository TuLieuKhac => tulieukhac ??= new TuLieuKhacRepository(Connection);
    public TuLieuVideoRepository TuLieuVideo => tulieuvideo ??= new TuLieuVideoRepository(Connection);
    public RanhGioiHuyenRepository RanhGioiHuyen => ranhgioihuyen ??= new RanhGioiHuyenRepository(Connection);
    public RanhGioiXaRepository RanhGioiXa => ranhgioixa ??= new RanhGioiXaRepository(Connection);
    public MemberRepository Member => member ??= new MemberRepository(Connection);
    public GiaoThongRepository GiaoThong => giaothong ??= new GiaoThongRepository(Connection);
    public ThuyHeRepository ThuyHe => thuyhe ??= new ThuyHeRepository(Connection);
    public MemberRoleRepository MemberRole => memberrole ??= new MemberRoleRepository(Connection);
    public MemberLoginRepository MemberLogin => memberlogin ??= new MemberLoginRepository(Connection);
    public HoChuaRepository HoChua => hoChua ??= new HoChuaRepository(Connection);
    public Helper Helper => helper ??= new Helper(Connection);
    public RoleRepository Role => role ??= new RoleRepository(Connection);
    public RefreshTokenRepository RefreshToken => refreshtoken ??= new RefreshTokenRepository(Connection);
    public ChayRungRepository ChayRung => chayrung ??= new ChayRungRepository(Connection);
    public KhuNeoDauRepository KhuNeoDau => khuneodau ??= new KhuNeoDauRepository(Connection);
    public DanhBaDTRepository DanhBaDT => danhBaDT ??= new DanhBaDTRepository(Connection);
    public QuanDaoHSTSRepository QuanDaoHSTS => quanDaoHSTS ??= new QuanDaoHSTSRepository(Connection);
    public HistoryRepository History => history ??= new HistoryRepository(Connection);
}